/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/dotfiles/add.sh
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/dotfiles/README.md
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/.config/awesome
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/.config/neofetch
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/.config/alacritty.yml
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/.config/picom.conf
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/.config/nvim
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/.fehbg
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/.bashrc
/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME add $HOME/.gitconfig
