vim.keymap.set("n", "<leader>tnw", "<cmd>silent! !tmux new-window -c %:p:h<CR>")
vim.keymap.set("n", "<leader>tsh", "<cmd>silent! !tmux split-window -h -c %:p:h<CR>")
vim.keymap.set("n", "<leader>tss", "<cmd>silent! !tmux split-window -h -p 25 -c %:p:h<CR>")
vim.keymap.set("n", "<C-l>", "<cmd>silent! !tmux select-pane -R<CR>")
vim.keymap.set("n", "<C-h>", "<cmd>silent! !tmux select-pane -L<CR>")
vim.keymap.set("n", "<C-j>", "<cmd>silent! !tmux select-pane -D<CR>")
vim.keymap.set("n", "<C-k>", "<cmd>silent! !tmux select-pane -U<CR>")
